version: '3'

services:
  redis-compose:
    image: redis
    command: redis-server --requirepass SUASENHA --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/postgresql/data